export const descriptionFront = "Generated by create next app - Front";
export const descriptionAuth = "Generated by create next app - Auth";
export const descriptionDashboard = "Generated by create next app - Dashboard";

export const titleFront = "Generated by create next app - Front";
export const titleAuth = "Generated by create next app - Auth";
export const titleDashboard = "Generated by create next app - Dashboard";
