import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../globals.css";

import { cn } from "@/lib/utils";
import connectMongo from "@/lib/dbConnect/connectMongo";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const conn = await connectMongo();
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
